### ISSUE TITLE
non static method getExtendedTypes()

### ISSUE THREAD

**Issue by Loocos** [FitraTech/SyliusFacebookMessengerPlugin#7]
Hello,

When upgrading Sylius, it throw an error because of your non static method of getExtendedTypes() in ChannelTypeExtension

This :
    public function getExtendedTypes(): array
Must be :
    public static function getExtendedTypes(): iterable

Thank you

**Comment by htaoufikallah** [comment]
a new version is released check if fix the issue for you

**Comment by htaoufikallah** [comment]
@Loocos should this issue be closed?

**Comment by Loocos** [comment]
> @Loocos should this issue be closed?

I didn't check but must be good now! So yes it can be closed, thank you @htaoufikallah
